### ISSUE TITLE
Cookie Hinweis

### ISSUE THREAD

**Issue by riekehieke** [riekehieke/website#10]
Wenn Google Analytics genutzt wird: Cookie Hinweis einfügen

**Comment by jonaskuske** [comment]
Oder aber: kein Google Analytics, in YouTube Links das `youtube.com` durch `youtube-nocookie.com` ersetzen (also dann `https://www.youtube-nocookie.com/watch?v=id`) ersetzen und kein Cookie Banner nötig (:
